name: instrument_setting
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - anyio=4.4.0=pyhd8ed1ab_0
  - appnope=0.1.4=pyhd8ed1ab_0
  - argon2-cffi=23.1.0=pyhd8ed1ab_0
  - arrow=1.3.0=pyhd8ed1ab_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - async-lru=2.0.4=pyhd8ed1ab_0
  - attrs=23.2.0=pyh71513ae_0
  - babel=2.14.0=pyhd8ed1ab_0
  - beautifulsoup4=4.12.3=pyha770c72_0
  - bleach=6.1.0=pyhd8ed1ab_0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.7.4
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.0
  - certifi=2024.7.4=pyhd8ed1ab_0
  - cffi=1.16.0
  - chardet=5.2.0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.2.2=pyhd8ed1ab_0
  - cycler=0.12.1=pyhd8ed1ab_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - deprecated=1.2.14=pyh1a96a4e_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - executing=2.0.1=pyhd8ed1ab_0
  - expat=2.6.2
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_2
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.53.1
  - fqdn=1.5.1=pyhd8ed1ab_0
  - freetype-py=2.3.0=pyhd8ed1ab_0
  - h11=0.14.0=pyhd8ed1ab_0
  - h2=4.1.0=pyhd8ed1ab_0
  - hpack=4.0.0=pyh9f0ad1d_0
  - httpcore=1.0.5=pyhd8ed1ab_0
  - httpx=0.27.0=pyhd8ed1ab_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - icu=75.1
  - idna=3.7=pyhd8ed1ab_0
  - importlib-metadata=8.2.0=pyha770c72_0
  - importlib_metadata=8.2.0=hd8ed1ab_0
  - importlib_resources=6.4.0=pyhd8ed1ab_0
  - ipykernel=6.29.5=pyh57ce528_0
  - ipython=8.26.0=pyh707e725_0
  - ipywidgets=8.1.3=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.4=pyhd8ed1ab_0
  - json5=0.9.25=pyhd8ed1ab_0
  - jsonpointer=3.0.0
  - jsonschema=4.23.0=pyhd8ed1ab_0
  - jsonschema-specifications=2023.12.1=pyhd8ed1ab_0
  - jsonschema-with-format-nongpl=4.23.0=hd8ed1ab_0
  - jupyter=1.0.0=pyhd8ed1ab_10
  - jupyter-lsp=2.2.5=pyhd8ed1ab_0
  - jupyter_client=8.6.2=pyhd8ed1ab_0
  - jupyter_console=6.6.3=pyhd8ed1ab_0
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0=pyhd8ed1ab_0
  - jupyter_server=2.14.2=pyhd8ed1ab_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_0
  - jupyterlab=4.2.4=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_1
  - jupyterlab_server=2.27.3=pyhd8ed1ab_0
  - jupyterlab_widgets=3.0.11=pyhd8ed1ab_0
  - kiwisolver=1.4.5
  - krb5=1.21.3
  - lerc=4.0.0
  - libblas=3.9.0
  - libboost=1.84.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcxx=18.1.8
  - libedit=3.1.20191231
  - libexpat=2.6.2
  - libgfortran
  - libgfortran5=13.2.0
  - libiconv=1.17
  - libjpeg-turbo=2.1.5.1
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libpq=16.3
  - librdkit=2024.03.5
  - libsqlite=3.46.0
  - libxslt=1.1.39
  - libzlib
  - llvm-openmp=18.1.8
  - llvmlite=0.43.0
  - lxml=5.2.2
  - matchms=0.27.0=pyhdfd78af_0
  - matplotlib-base=3.9.1
  - matplotlib-inline=0.1.7
  - mistune=3.0.2=pyhd8ed1ab_0
  - munkres=1.0.7=py_1
  - nbclient=0.10.0=pyhd8ed1ab_0
  - nbconvert=7.16.4=hd8ed1ab_1
  - nbconvert-core=7.16.4=pyhd8ed1ab_1
  - nbconvert-pandoc=7.16.4=hd8ed1ab_1
  - nbformat=5.10.4=pyhd8ed1ab_0
  - ncurses=6.5
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - networkx=3.3=pyhd8ed1ab_1
  - notebook=7.2.1=pyhd8ed1ab_0
  - notebook-shim=0.2.4=pyhd8ed1ab_0
  - numba=0.60.0
  - numpy=1.24.4
  - overrides=7.7.0=pyhd8ed1ab_0
  - packaging=24.1=pyhd8ed1ab_0
  - pandas=2.2.2
  - pandoc=3.3
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_0
  - pcre2=10.44
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pickydict=0.4.0=pyhd8ed1ab_0
  - pip=24.0=pyhd8ed1ab_0
  - pixman
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
  - platformdirs=4.2.2=pyhd8ed1ab_0
  - pooch=1.8.2=pyhd8ed1ab_0
  - prometheus_client=0.20.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.47=pyha770c72_0
  - prompt_toolkit=3.0.47=hd8ed1ab_0
  - psutil=6.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pubchempy=1.0.4=pyh864c0ab_2
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - pycairo=1.26.1
  - pycparser=2.22=pyhd8ed1ab_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - pyparsing=3.1.2=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - pyteomics=4.7.2
  - python=3.11
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-fastjsonschema=2.20.0=pyhd8ed1ab_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2024.1=pyhd8ed1ab_0
  - python_abi=3.11=4_cp311
  - pytz=2024.1=pyhd8ed1ab_0
  - pyyaml=6.0.1
  - qhull=2020.2
  - qtconsole-base=5.5.2=pyha770c72_0
  - qtpy=2.4.1=pyhd8ed1ab_0
  - rdkit=2024.03.5
  - readline=8.2
  - referencing=0.35.1=pyhd8ed1ab_0
  - reportlab=4.2.2
  - requests=2.32.3=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_0
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rlpycairo=0.2.0=pyhd8ed1ab_0
  - rpds-py=0.19.1
  - scipy=1.10.1
  - send2trash=1.8.3=pyh31c8845_0
  - setuptools=71.0.4=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - sniffio=1.3.1=pyhd8ed1ab_0
  - soupsieve=2.5=pyhd8ed1ab_1
  - sparsestack=0.5.0=pyhd8ed1ab_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - terminado=0.18.1=pyh31c8845_0
  - tinycss2=1.3.0=pyhd8ed1ab_0
  - tk=8.6.13
  - tomli=2.0.1=pyhd8ed1ab_0
  - tornado=6.4.1
  - tqdm=4.66.4=pyhd8ed1ab_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - types-python-dateutil=2.9.0.20240316=pyhd8ed1ab_0
  - typing-extensions=4.12.2=hd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - typing_utils=0.1.0=pyhd8ed1ab_0
  - tzdata=2024a=h0c530f3_0
  - uri-template=1.3.0=pyhd8ed1ab_0
  - urllib3=2.2.2=pyhd8ed1ab_1
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - webcolors=24.6.0=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_2
  - websocket-client=1.8.0=pyhd8ed1ab_0
  - wheel=0.43.0=pyhd8ed1ab_1
  - widgetsnbextension=4.0.11=pyhd8ed1ab_0
  - wrapt=1.16.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.19.2=pyhd8ed1ab_0
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - absl-py==2.1.0
      - aiohappyeyeballs==2.4.3
      - aiohttp==3.10.10
      - aiosignal==1.3.1
      - altair==5.4.1
      - appdirs==1.4.4
      - click==8.1.8
      - cloudpathlib==0.19.0
      - cloudpickle==3.1.0
      - configspace==1.2.1
      - dask==2024.12.1
      - dask-jobqueue==0.9.0
      - depthcharge-ms==0.4.8
      - dill==0.3.9
      - distributed==2024.12.1
      - einops==0.8.0
      - emcee==3.1.6
      - fastobo==0.12.3
      - filelock==3.16.1
      - frozenlist==1.4.1
      - fsspec==2024.9.0
      - grpcio==1.67.1
      - joblib==1.4.2
      - lark==1.2.2
      - lightning==2.4.0
      - lightning-utilities==0.11.8
      - locket==1.0.0
      - markdown==3.7
      - more-itertools==10.5.0
      - mpmath==1.3.0
      - msgpack==1.1.0
      - multidict==6.1.0
      - narwhals==1.13.1
      - partd==1.4.2
      - polars==1.9.0
      - propcache==0.2.0
      - protobuf==5.28.3
      - psims==1.3.4
      - pyarrow==17.0.0
      - pylance==0.18.2
      - pynisher==1.0.10
      - pyrfr==0.9.0
      - pytorch-lightning==2.4.0
      - regex==2024.11.6
      - scikit-learn==1.5.2
      - selfies==2.1.2
      - smac==2.2.0
      - sortedcontainers==2.4.0
      - spectrum-utils==0.4.2
      - sympy==1.13.3
      - tblib==3.0.0
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.5.0
      - toolz==1.0.0
      - torch==2.4.1
      - torchaudio==2.4.1
      - torchmetrics==1.4.3
      - torchvision==0.19.1
      - werkzeug==3.1.3
      - yarl==1.15.4
      - zict==3.0.0
