name: instrument_setting
channels:
  - pytorch
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip

  - libstdcxx-ng
  - numpy>=1.26,<2.0
  - pandas>=2.2
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - networkx
  - altair



  - pytorch
  - torchvision
  - torchaudio
  - lightning
  - torchmetrics


  - jupyter
  - tqdm
  - pyyaml
  - hdf5
  - pillow
  - requests
  - sqlalchemy
  - rdkit

  - pip:
      - matchms
      - depthcharge-ms
      - ms-entropy
      - ppx
      - psims
      - pyteomics
      - spectrum_utils
      - selfies
      - pubchempy

      - azure-storage-blob
      - azure-storage-file-datalake
      - google-cloud-storage
      - boto3
      - dask
      - distributed

      - lancedb
      - lance
      - polars
      - einops
      - pydantic
      - torch-summary